baseURL = "https://www.hyrrot.jp"
title = "Pays des Merveilles d'Hyrrot"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
googleAnalytics = "G-39Z1DG1M4C"

[minify]
disableXML = true

[languages.ja]
languageName = ":jp:"
languageAltTitle= "日本語"
weight = 1

  [languages.ja.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [languages.ja.profileMode]
  enabled = true
  title = "Hyrrot"
  subtitle = """
  データエンジニアリング、DevOpsソリューションにおけるソフトウェアエンジニア
  """

    [[languages.ja.profileMode.buttons]]
    name = "About"
    url = "about"

    [[languages.ja.profileMode.buttons]]
    name = "Blog"
    url = "posts"



[[languages.ja.menu.main]]
name = "アーカイブ"
url = "archives"
weight = 5

[[languages.ja.menu.main]]
name = "検索"
url = "search/"
weight = 10

[[languages.ja.menu.main]]
name = "タグ"
url = "tags/"
weight = 15

[[languages.ja.menu.main]]
name = "カテゴリ"
url = "categories/"
weight = 20

[languages.en]
languageName = ":gb:"
languageAltTitle = "English"
weight = 1
title = "Pays des Merveilles d'Hyrrot"

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [languages.en.profileMode]
  enabled = true
  title = "Hyrrot"
  subtitle = "Software Engineer in Data Engineering, and DevOps solutions"

    [[languages.en.profileMode.buttons]]
    name = "About"
    url = "about"

    [[languages.en.profileMode.buttons]]
    name = "Blog"
    url = "posts"

[[languages.en.menu.main]]
name = "Archive"
url = "archives/"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 15

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 20



[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Hyrrot's website"
author = "Hyrrot"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = true
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Pays des Merveilles d'Hyrrot"
  Content = """
I am a skilled software developer with 10+ years of experience in leveraging technologies in “Big Data”, web applications frontend / backend, infrastructure and DevOps area. I also solve business problems in organizations by owning the entire process of delivering solutions for them.

"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/hyrrot"


  [[params.socialIcons]]
  name = "Twitter"
  url = "https://www.twitter.com/hyrrot/"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/hirobumi-takahashi-7ba45538/"

  [[params.socialIcons]]
  name = "RsS"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/hyrrot/hyrrot.github.io/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

[markup.goldmark.renderer]
unsafe = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
